version: '3.7'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:27017 -timeout 20s sh -c "npm install && node ./bin/www"
    restart: always
    tty: true
    volumes:
      - ./node:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    # it was not necessary to decrypt the password from !Base64 to plain text 
    build: ./mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_PASSWORD: bWV0ZW9yaGlyaW5nCg==
      MONGO_REPLICA_HOST: ac-nhcvxhf-shard-00-00.bebrwbu.mongodb.net
      MONGODB_DATABASE: message
    volumes:
      - ./db:/data/db
