name: cdmateusclira

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.1'

      - name: Install dependencies
        run: npm install

      - run: npm run build --if-present
      - run: npm test

  docker_node:
    name: Docker - Node
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/node/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image to dockerhub
        uses: docker/build-push-action@v4
        with:
          file: ./app/node/Dockerfile
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.METEOR_TOKEN }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/meteorapp:${{ github.sha }}

  publish:
    name: Publish
    needs: docker_mongo
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
          run:
            working-directory: ./app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update readme
        run: |
          echo "## Docker Images" >> README.md
          echo "" >> README.md
          echo "### Node" >> README.md
          echo "" >> README.md
          echo "![Docker Image Version](https://img.shields.io/docker/v/${{ secrets.DOCKERHUB_USERNAME }}/meteorapp:${{ github.sha }}" >> README.md
          echo "" >> README.md
          echo "### DockerHub" >> README.md
          echo "" >> README.md
          echo "### GitHub" >> README.md
          echo "" >> README.md

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -am "updating terraform"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.METEOR_TOKEN }}
          branch: main
          repository: mateusclira/hiring-devops-mateusclira 

      