name: cicdmateusclira

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.1'

      - name: Install dependencies
        run: npm install
      
      - run: npm install jest
      - run: npm run build --if-present
      - run: npm test

  deploy_dev:
    name: Docker - Node
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./app/node/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image to dockerhub
        uses: docker/build-push-action@v4
        with:
          file: ./app/node/Dockerfile
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.METEOR_TOKEN }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/meteorapp:${{ github.sha }}

  publish_dev:
    name: Publish in DEV
    needs: docker_node
    runs-on: ubuntu-latest
    environment: dev
    if: github.ref == 'refs/heads/develop'
    defaults:
          run:
            working-directory: ./app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update readme
        run: |
          echo "## Docker Images" >> README.md
          echo "" >> README.md
          echo "### Node" >> README.md
          echo "" >> README.md
          echo "![Docker Image Version (latest semver)](https://img.shields.io/docker/v/${{ secrets.DOCKERHUB_USERNAME }}/meteorapp?sort=semver)" >> README.md
          echo "" >> README.md
          echo "### DockerHub" >> README.md
          echo "" >> README.md
          echo "[DockerHub](https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }})" >> README.md
          echo "" >> README.md
          echo "### GitHub" >> README.md
          echo "" >> README.md

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -am "testing cicd

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.METEOR_TOKEN }}
          branch: develop
          repository: mateusclira/hiring-devops-mateusclira 

  deploy_prod:
    name: AWS - Node | PRD
    needs: build
    runs-on: ubuntu-latest
    environment: prd
    defaults:
      run:
        working-directory: ./app/node/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          role-to-assume: arn:aws:iam::608636080729:role/github-actions
          aws-region: us-east-1

      - run: docker build -t mateusclira .
      - run: docker tag mateusclira:latest public.ecr.aws/q3k0a0y5/mateusclira:latest

      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: mateusclira:latest

  publish_prd:
    name: Publish in PRD
    needs: deploy_prod
    runs-on: ubuntu-latest
    environment: prd
    if: github.ref == 'refs/heads/main'
    defaults:
          run:
            working-directory: ./app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update readme
        run: |
          echo "## Docker Images" >> README.md
          echo "" >> README.md
          echo "### Node" >> README.md
          echo "" >> README.md
          echo "![Docker Image Version (latest semver)](https://img.shields.io/docker/v/${{ secrets.DOCKERHUB_USERNAME }}/meteorapp?sort=semver)" >> README.md
          echo "" >> README.md
          echo "### DockerHub" >> README.md
          echo "" >> README.md
          echo "[DockerHub](https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }})" >> README.md
          echo "" >> README.md
          echo "### GitHub" >> README.md
          echo "" >> README.md

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -am "updating terraform"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.METEOR_TOKEN }}
          branch: main
          repository: mateusclira/hiring-devops-mateusclira 
